"""Data quality report generation."""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path


DEFAULT_REPORTS_DIRECTORY = Path("reports")
LATEST_REPORT_NAME = "data_quality_report_latest.txt"


@dataclass(frozen=True)
class DataQualityReport:
    """Summary of one data quality run."""

    records_processed: int
    valid_records: int
    duplicate_records: int
    missing_values_fixed: int
    invalid_urls: int
    rejected_records: int
    quality_score: float
    generated_at: datetime
    issue_messages: list[str] = field(default_factory=list)


def calculate_quality_score(valid_records: int, records_processed: int) -> float:
    """Calculate data quality score as a percentage."""
    if records_processed == 0:
        return 100.0

    return round((valid_records / records_processed) * 100, 2)


def _format_percentage(value: float) -> str:
    """Format a percentage without noisy decimals."""
    numeric_value = float(value)
    if numeric_value.is_integer():
        return f"{int(numeric_value)}%"

    return f"{numeric_value:.2f}%"


def format_quality_report(report: DataQualityReport) -> str:
    """
    Format a data quality report as plain text.

    Args:
        report: Report values generated by quality checks.

    Returns:
        str: Human-readable report content.
    """
    lines = [
        "-----------------------------------",
        "DATA QUALITY REPORT",
        "-----------------------------------",
        f"Generated At         : {report.generated_at.isoformat()}",
        f"Records Processed   : {report.records_processed}",
        f"Valid Records       : {report.valid_records}",
        f"Duplicate Records   : {report.duplicate_records}",
        f"Missing Values Fixed: {report.missing_values_fixed}",
        f"Invalid URLs        : {report.invalid_urls}",
        f"Rejected Records    : {report.rejected_records}",
        f"Quality Score       : {_format_percentage(report.quality_score)}",
    ]

    if report.issue_messages:
        lines.extend(["", "Issues:"])
        lines.extend(f"- {message}" for message in report.issue_messages)

    lines.append("-----------------------------------")
    return "\n".join(lines) + "\n"


def save_quality_report(
    report: DataQualityReport,
    reports_directory: Path = DEFAULT_REPORTS_DIRECTORY,
) -> Path:
    """
    Save a timestamped quality report and refresh the latest report file.

    Args:
        report: Data quality report to persist.
        reports_directory: Directory where report files are stored.

    Returns:
        Path: Path to the timestamped report file.
    """
    reports_directory.mkdir(exist_ok=True)
    timestamp = report.generated_at.strftime("%Y%m%d_%H%M%S")
    report_path = reports_directory / f"data_quality_report_{timestamp}.txt"
    report_content = format_quality_report(report)

    report_path.write_text(report_content, encoding="utf-8")
    latest_report_path = reports_directory / LATEST_REPORT_NAME
    latest_report_path.write_text(report_content, encoding="utf-8")

    return report_path
